### ISSUE TITLE
What does an instruction look like ?

### ISSUE THREAD

**Issue by Hasenn** [dev-sys-do/do-core1#24]
The Readme states the instructions are 32bit wide but still explains that " a do-core1 instruction can be split into an operation code (opcode), the first operand (op0) and the second operand (op1). The opcode is 6 bits long, and operands are 5 bits long:"

So that would be 16 bit wide,

Did we change the word size only or is the new instruction shape undocumented ?

**Comment by sameo** [comment]
We will need the remaining bits for immediate addressing, where the last argument is a signed or unsigned constant that could use up to 21 bits.

**Comment by Hasenn** [comment]
Allright, thanks
